language: ruby
rvm:
- 2.4.2
script:
 - rubocop
install: gem install rubocop -v 0.50.0
notifications:
  irc:
    channels:
      - "irc.chew.pro#Chewbotcca"
    template:
      - "Build #%{build_number}: %{message} Time Elapsed: %{elapsed_time}. %{build_url}"
